defmodule Layouts.Keychron do
  def k2v2 do
    [
      [
        %{size: 1, keycode: 53, name: "esc"},
        %{size: 1, keycode: 122, name: "F1"},
        %{size: 1, keycode: 120, name: "F2"},
        %{size: 1, keycode: 99, name: "F3"},
        %{size: 1, keycode: 118, name: "F4"},
        %{size: 1, keycode: 96, name: "F5"},
        %{size: 1, keycode: 97, name: "F6"},
        %{size: 1, keycode: 98, name: "F7"},
        %{size: 1, keycode: 100, name: "F8"},
        %{size: 1, keycode: 101, name: "F9"},
        %{size: 1, keycode: 109, name: "F10"},
        %{size: 1, keycode: 103, name: "F11"},
        %{size: 1, keycode: 111, name: "F12"},
        %{size: 1, keycode: -1, name: "screenshot"},
        %{size: 1, keycode: 117, name: "del"},
        %{size: 1, keycode: -1, name: "lights"}
      ],
      [
        %{size: 1, keycode: 50, name: "`~"},
        %{size: 1, keycode: 18, name: "1!"},
        %{size: 1, keycode: 19, name: "2@"},
        %{size: 1, keycode: 20, name: "3#"},
        %{size: 1, keycode: 21, name: "4$"},
        %{size: 1, keycode: 23, name: "5%"},
        %{size: 1, keycode: 22, name: "6^"},
        %{size: 1, keycode: 26, name: "7&"},
        %{size: 1, keycode: 28, name: "8*"},
        %{size: 1, keycode: 25, name: "9("},
        %{size: 1, keycode: 29, name: "0)"},
        %{size: 1, keycode: 27, name: "-_"},
        %{size: 1, keycode: 24, name: "=+"},
        %{size: 2, keycode: 51, name: "backspace"},
        %{size: 1, keycode: 116, name: "pg_up"}
      ],
      [
        %{size: 1.5, keycode: 50, name: "tab"},
        %{size: 1, keycode: 12, name: "Q"},
        %{size: 1, keycode: 13, name: "W"},
        %{size: 1, keycode: 14, name: "E"},
        %{size: 1, keycode: 15, name: "R"},
        %{size: 1, keycode: 17, name: "T"},
        %{size: 1, keycode: 16, name: "Y"},
        %{size: 1, keycode: 32, name: "U"},
        %{size: 1, keycode: 34, name: "I"},
        %{size: 1, keycode: 31, name: "O"},
        %{size: 1, keycode: 35, name: "P"},
        %{size: 1, keycode: 33, name: "[{"},
        %{size: 1, keycode: 30, name: "]}"},
        %{size: 1.5, keycode: 42, name: "\\|"},
        %{size: 1, keycode: 121, name: "pg_down"}
      ],
      [
        # %{size: 1.75, keycode: 57, name: "caps"},
        %{size: 1.75, keycode: 62, name: "ctrl"},
        %{size: 1, keycode: 0, name: "A"},
        %{size: 1, keycode: 1, name: "S"},
        %{size: 1, keycode: 2, name: "D"},
        %{size: 1, keycode: 3, name: "F"},
        %{size: 1, keycode: 5, name: "G"},
        %{size: 1, keycode: 4, name: "H"},
        %{size: 1, keycode: 38, name: "J"},
        %{size: 1, keycode: 40, name: "K"},
        %{size: 1, keycode: 37, name: "L"},
        %{size: 1, keycode: 41, name: ";:"},
        %{size: 1, keycode: 39, name: "\'\""},
        %{size: 2.25, keycode: 36, name: "enter"},
        %{size: 1, keycode: 115, name: "home"}
      ],
      [
        %{size: 2.25, keycode: 56, name: "shift"},
        %{size: 1, keycode: 6, name: "Z"},
        %{size: 1, keycode: 7, name: "X"},
        %{size: 1, keycode: 8, name: "C"},
        %{size: 1, keycode: 9, name: "V"},
        %{size: 1, keycode: 11, name: "B"},
        %{size: 1, keycode: 45, name: "N"},
        %{size: 1, keycode: 46, name: "M"},
        %{size: 1, keycode: 43, name: ",<"},
        %{size: 1, keycode: 47, name: ".>"},
        %{size: 1, keycode: 44, name: "/?"},
        %{size: 1.75, keycode: 60, name: "shift"},
        %{size: 1, keycode: 126, name: "up"},
        %{size: 1, keycode: 119, name: "end"}
      ],
      [
        %{size: 1.25, keycode: 59, name: "ctrl"},
        %{size: 1.25, keycode: 58, name: "option"},
        %{size: 1.25, keycode: 55, name: "cmd"},
        %{size: 6.25, keycode: 49, name: "space"},
        %{size: 1, keycode: 54, name: "cmd"},
        %{size: 1, keycode: 63, name: "fn"},
        %{size: 1, keycode: 61, name: "option"},
        %{size: 1, keycode: 123, name: "left"},
        %{size: 1, keycode: 125, name: "down"},
        %{size: 1, keycode: 124, name: "right"}
      ]
    ]
  end
end
